"""SelfTool v2: agent self-evolution — inspect, modify, and invoke runtime state."""

from __future__ import annotations

import copy
import inspect
from typing import TYPE_CHECKING, Any

from loguru import logger

from nanobot.agent.tools.base import Tool

if TYPE_CHECKING:
    from nanobot.agent.loop import AgentLoop


def _has_real_attr(obj: Any, key: str) -> bool:
    """Check if obj has a real (explicitly set) attribute, not auto-generated by mock."""
    # Check instance dict
    if isinstance(obj, dict):
        return key in obj
    d = getattr(obj, "__dict__", None)
    if d is not None and key in d:
        return True
    # Check class-level attributes (but not mock auto-attrs)
    for cls in type(obj).__mro__:
        if key in cls.__dict__:
            return True
    return False


class SelfTool(Tool):
    """Inspect and modify your own runtime state, navigate related objects,
    invoke methods, and save/restore configuration snapshots."""

    # Only truly dangerous attributes that would crash or lockout.
    BLOCKED = frozenset({
        "bus", "provider", "_running",
        # Self-tool internal state
        "_config_defaults", "_runtime_vars", "_unregistered_tools",
        "_critical_tool_backup", "_config_snapshots",
    })

    _DENIED_ATTRS = frozenset({
        "__class__", "__dict__", "__bases__", "__subclasses__", "__mro__",
        "__init__", "__new__", "__reduce__", "__getstate__", "__setstate__",
        "__del__", "__call__", "__getattr__", "__setattr__", "__delattr__",
        "__code__", "__globals__", "func_globals", "func_code",
    })

    RESTRICTED: dict[str, dict[str, Any]] = {
        "max_iterations":        {"type": int, "min": 1,   "max": 100},
        "context_window_tokens": {"type": int, "min": 4096, "max": 1_000_000},
        "model":                 {"type": str, "min_len": 1},
    }

    _MAX_VALUE_ELEMENTS = 1024
    _MAX_RUNTIME_KEYS = 64

    def __init__(self, loop: AgentLoop) -> None:
        self._loop = loop
        self._channel = ""
        self._chat_id = ""

    def __deepcopy__(self, memo: dict[int, Any]) -> SelfTool:
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        result._loop = self._loop
        result._channel = self._channel
        result._chat_id = self._chat_id
        return result

    def set_context(self, channel: str, chat_id: str) -> None:
        self._channel = channel
        self._chat_id = chat_id

    @property
    def name(self) -> str:
        return "self"

    @property
    def description(self) -> str:
        return (
            "Inspect and modify your own runtime state, navigate related objects, "
            "invoke methods, and save/restore configuration snapshots. "
            "Use 'inspect' with dot-path to explore (e.g. 'subagents._running_tasks'), "
            "'modify' to change values, 'call' to invoke methods, "
            "'list_tools' to see registered tools, 'manage_tool' to register/unregister, "
            "'snapshot'/'restore' to save/load config templates."
        )

    @property
    def parameters(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "inspect", "modify", "call",
                        "list_tools", "manage_tool",
                        "snapshot", "restore", "list_snapshots", "reset",
                    ],
                    "description": "Action to perform",
                },
                "key":        {"type": "string", "description": "Dot-path for inspect/modify/reset"},
                "value":      {"description": "New value (for modify)"},
                "method":     {"type": "string", "description": "Dot-path to method (for call)"},
                "args":       {"type": "object", "description": "Arguments for call"},
                "name":       {"type": "string", "description": "Tool name or snapshot name"},
                "manage_action": {"type": "string", "description": "'register' or 'unregister'"},
            },
            "required": ["action"],
        }

    def _audit(self, action: str, detail: str) -> None:
        session = f"{self._channel}:{self._chat_id}" if self._channel else "unknown"
        logger.info("self.{} | {} | session:{}", action, detail, session)

    # ------------------------------------------------------------------
    # Path resolution
    # ------------------------------------------------------------------

    def _resolve_path(self, path: str) -> tuple[Any, str | None]:
        """Resolve a dot-path from the loop root.

        Returns (resolved_object, None) on success,
        or (None, error_string) on failure.
        """
        parts = path.split(".")
        obj = self._loop
        for part in parts:
            if part in self._DENIED_ATTRS or part.startswith("__"):
                return None, f"'{part}' is not accessible"
            if part in self.BLOCKED:
                return None, f"'{part}' is not accessible"
            try:
                if isinstance(obj, dict):
                    if part in obj:
                        obj = obj[part]
                    else:
                        return None, f"'{part}' not found in dict"
                else:
                    obj = getattr(obj, part)
            except (KeyError, AttributeError) as e:
                return None, f"'{part}' not found: {e}"
        return obj, None

    @staticmethod
    def _validate_key(key: str | None, label: str = "key") -> str | None:
        if not key or not key.strip():
            return f"Error: '{label}' cannot be empty or whitespace"
        return None

    # ------------------------------------------------------------------
    # Smart formatting
    # ------------------------------------------------------------------

    @staticmethod
    def _format_value(val: Any, key: str = "") -> str:
        """Format a value for inspect output."""
        if val is None:
            return f"{key}: None" if key else "None"

        # Simple scalar
        if isinstance(val, (bool, int, float, str)):
            text = f"{key}: {val!r}" if key else repr(val)
            return text

        # Callable → method hint
        if callable(val):
            name = getattr(val, "__name__", str(val))
            sig = ""
            try:
                sig = str(inspect.signature(val))
            except (ValueError, TypeError):
                pass
            label = f"{key}." if key else ""
            return f"method {label}{name}{sig} — use 'call' action to invoke"

        # Dict
        if isinstance(val, dict):
            r = repr(val)
            if len(r) > 2000:
                r = r[:2000] + "... (truncated)"
            prefix = f"{key}: " if key else ""
            return f"{prefix}{r}"

        # List / tuple
        if isinstance(val, (list, tuple)):
            preview = repr(val[:20])
            if len(val) > 20:
                preview = preview.rstrip("]") + f", ...] ({len(val)} items)"
            prefix = f"{key}: " if key else ""
            return f"{prefix}{preview}"

        # Has tool_names → ToolRegistry-like
        if hasattr(val, "tool_names"):
            names = val.tool_names
            return f"tools: {len(names)} registered — {names}"

        # Has _running_tasks → SubagentManager-like
        if hasattr(val, "_running_tasks") and isinstance(getattr(val, "_running_tasks"), dict):
            tasks = val._running_tasks
            count = len(tasks)
            ids = list(tasks.keys())[:10]
            return f"subagents: {count} running — {ids}"

        # Generic object → list public attrs
        attrs = [a for a in dir(val) if not a.startswith("_") and not callable(getattr(val, a, None))]
        cls_name = type(val).__name__
        if attrs:
            return f"<{cls_name}> attributes: {attrs[:20]}"
        return f"<{cls_name}>"

    def _inspect_all(self) -> str:
        """Full state summary."""
        loop = self._loop
        parts: list[str] = []
        for k in self.RESTRICTED:
            parts.append(f"{k}: {getattr(loop, k, None)!r}")
        # Runtime vars
        rv = loop._runtime_vars
        if rv:
            rv_repr = repr(rv)
            if len(rv_repr) > 2000:
                rv_repr = rv_repr[:2000] + "... (truncated)"
            parts.append(f"_runtime_vars: {rv_repr}")
        return "\n".join(parts)

    # ------------------------------------------------------------------
    # Action dispatch
    # ------------------------------------------------------------------

    async def execute(
        self,
        action: str,
        key: str | None = None,
        value: Any = None,
        method: str | None = None,
        args: dict[str, Any] | None = None,
        name: str | None = None,
        manage_action: str | None = None,
        **_kwargs: Any,
    ) -> str:
        if action == "inspect":
            return self._inspect(key)
        if action == "modify":
            return self._modify(key, value)
        if action == "call":
            return await self._call(method, args)
        if action == "list_tools":
            return self._list_tools()
        if action == "manage_tool":
            return self._manage_tool(manage_action, name)
        if action == "snapshot":
            return self._snapshot(name)
        if action == "restore":
            return self._restore(name)
        if action == "list_snapshots":
            return self._list_snapshots()
        if action == "reset":
            return self._reset(key)
        # Backward compat aliases
        if action == "unregister_tool":
            return self._manage_tool("unregister", name)
        if action == "register_tool":
            return self._manage_tool("register", name)
        return f"Unknown action: {action}"

    # -- inspect --

    def _inspect(self, key: str | None) -> str:
        if not key:
            return self._inspect_all()

        # Direct blocked check for top-level key
        top = key.split(".")[0]
        if top in self._DENIED_ATTRS or top.startswith("__"):
            return f"Error: '{top}' is not accessible"

        obj, err = self._resolve_path(key)
        if err:
            return f"Error: {err}"

        # Check if it's actually a real value vs MagicMock auto-attr
        # For single-key top-level, check the loop really has it
        if "." not in key:
            if not _has_real_attr(self._loop, key):
                return f"Error: '{key}' not found"

        return self._format_value(obj, key)

    # -- modify --

    def _modify(self, key: str | None, value: Any) -> str:
        if err := self._validate_key(key):
            return err

        # Blocked check on top-level segment
        top = key.split(".")[0]
        if top in self.BLOCKED or top in self._DENIED_ATTRS or top.startswith("__"):
            self._audit("modify", f"BLOCKED {key}")
            return f"Error: '{key}' is protected and cannot be modified"

        # Dot-path modify: resolve parent, set leaf
        if "." in key:
            parent_path, leaf = key.rsplit(".", 1)
            parent, err = self._resolve_path(parent_path)
            if err:
                return f"Error: {err}"
            if isinstance(parent, dict):
                parent[leaf] = value
            else:
                setattr(parent, leaf, value)
            self._audit("modify", f"{key} = {value!r}")
            return f"Set {key} = {value!r}"

        # Top-level restricted
        if key in self.RESTRICTED:
            return self._modify_restricted(key, value)

        # Top-level free: setattr if exists, else runtime_vars
        return self._modify_free(key, value)

    def _modify_restricted(self, key: str, value: Any) -> str:
        spec = self.RESTRICTED[key]
        expected = spec["type"]
        if expected is int and isinstance(value, bool):
            return f"Error: '{key}' must be {expected.__name__}, got bool"
        if not isinstance(value, expected):
            try:
                value = expected(value)
            except (ValueError, TypeError):
                return f"Error: '{key}' must be {expected.__name__}, got {type(value).__name__}"
        old = getattr(self._loop, key)
        if "min" in spec and value < spec["min"]:
            return f"Error: '{key}' must be >= {spec['min']}"
        if "max" in spec and value > spec["max"]:
            return f"Error: '{key}' must be <= {spec['max']}"
        if "min_len" in spec and len(str(value)) < spec["min_len"]:
            return f"Error: '{key}' must be at least {spec['min_len']} characters"
        setattr(self._loop, key, value)
        self._audit("modify", f"{key}: {old!r} -> {value!r}")
        return f"Set {key} = {value!r} (was {old!r})"

    def _modify_free(self, key: str, value: Any) -> str:
        # If overwriting a real loop attribute, allow any value type (including complex objects).
        if _has_real_attr(self._loop, key):
            old = getattr(self._loop, key)
            setattr(self._loop, key, value)
            self._audit("modify", f"{key}: {old!r} -> {value!r}")
            return f"Set {key} = {value!r} (was {old!r})"

        # For new keys, enforce JSON-safe rules
        if callable(value):
            self._audit("modify", f"REJECTED callable {key}")
            return "Error: cannot store callable values"
        err = self._validate_json_safe(value)
        if err:
            self._audit("modify", f"REJECTED {key}: {err}")
            return f"Error: {err}"

        # Fallback: runtime_vars (with key cap)
        if key not in self._loop._runtime_vars and len(self._loop._runtime_vars) >= self._MAX_RUNTIME_KEYS:
            self._audit("modify", f"REJECTED {key}: max keys ({self._MAX_RUNTIME_KEYS}) reached")
            return f"Error: _runtime_vars is full (max {self._MAX_RUNTIME_KEYS} keys). Reset unused keys first."
        old = self._loop._runtime_vars.get(key)
        self._loop._runtime_vars[key] = value
        self._audit("modify", f"_runtime_vars.{key}: {old!r} -> {value!r}")
        return f"Set _runtime_vars.{key} = {value!r}"

    @classmethod
    def _validate_json_safe(cls, value: Any, depth: int = 0, elements: int = 0) -> str | None:
        if depth > 10:
            return "value nesting too deep (max 10 levels)"
        if isinstance(value, (str, int, float, bool, type(None))):
            return None
        if isinstance(value, list):
            elements += len(value)
            if elements > cls._MAX_VALUE_ELEMENTS:
                return f"value too large (max {cls._MAX_VALUE_ELEMENTS} total elements)"
            for i, item in enumerate(value):
                if err := cls._validate_json_safe(item, depth + 1, elements):
                    return f"list[{i}] contains {err}"
            return None
        if isinstance(value, dict):
            elements += len(value)
            if elements > cls._MAX_VALUE_ELEMENTS:
                return f"value too large (max {cls._MAX_VALUE_ELEMENTS} total elements)"
            for k, v in value.items():
                if not isinstance(k, str):
                    return f"dict key must be str, got {type(k).__name__}"
                if err := cls._validate_json_safe(v, depth + 1, elements):
                    return f"dict key '{k}' contains {err}"
            return None
        return f"unsupported type {type(value).__name__}"

    # -- call --

    async def _call(self, method: str | None, args: dict[str, Any] | None = None) -> str:
        if err := self._validate_key(method, "method"):
            return err

        obj, err = self._resolve_path(method)
        if err:
            return f"Error: {err}"
        if not callable(obj):
            return f"Error: '{method}' is not callable"
        try:
            result = obj(**(args or {}))
            # Await if coroutine
            if inspect.isawaitable(result):
                result = await result
            self._audit("call", method)
            return repr(result)
        except Exception as e:
            self._audit("call", f"{method} FAILED: {e}")
            return f"Error calling {method}: {e}"

    # -- list_tools --

    def _list_tools(self) -> str:
        tools = self._loop.tools
        names = tools.tool_names if hasattr(tools, "tool_names") else []
        lines: list[str] = []
        for n in names:
            t = tools.get(n) if hasattr(tools, "get") else None
            if t:
                desc = getattr(t, "description", "")[:80]
                ro = " [readonly]" if getattr(t, "read_only", False) else ""
                lines.append(f"  {n}{ro}: {desc}")
            else:
                lines.append(f"  {n}")
        return f"Tools ({len(names)}):\n" + "\n".join(lines)

    # -- manage_tool --

    def _manage_tool(self, manage_action: str | None, name: str | None) -> str:
        if err := self._validate_key(name, "name"):
            return err
        if not manage_action:
            return "Error: manage_action is required ('register' or 'unregister')"
        if manage_action == "unregister":
            return self._unregister_tool(name)
        if manage_action == "register":
            return self._register_tool(name)
        return f"Unknown manage_action: {manage_action}"

    def _unregister_tool(self, name: str) -> str:
        if name == "self":
            self._audit("unregister_tool", "BLOCKED self")
            return "Error: cannot unregister the 'self' tool (would cause lockout)"
        if not self._loop.tools.has(name):
            return f"Tool '{name}' is not currently registered"
        tool = self._loop.tools.get(name)
        self._loop._unregistered_tools[name] = tool
        self._loop.tools.unregister(name)
        self._audit("unregister_tool", name)
        return f"Unregistered tool '{name}'. Use register_tool to restore it."

    def _register_tool(self, name: str) -> str:
        if name not in self._loop._unregistered_tools:
            return f"Error: '{name}' was not previously unregistered (cannot register arbitrary tools)"
        tool = self._loop._unregistered_tools.pop(name)
        self._loop.tools.register(tool)
        self._audit("register_tool", name)
        return f"Re-registered tool '{name}'"

    # -- snapshots --

    def _snapshot(self, name: str | None) -> str:
        if err := self._validate_key(name, "name"):
            return err
        snap: dict[str, Any] = {}
        for k in self.RESTRICTED:
            snap[k] = getattr(self._loop, k, None)
        snap["_runtime_vars"] = copy.deepcopy(self._loop._runtime_vars)
        self._loop._config_snapshots[name] = snap
        self._audit("snapshot", name)
        return f"Snapshot '{name}' saved"

    def _restore(self, name: str | None) -> str:
        if err := self._validate_key(name, "name"):
            return err
        snap = self._loop._config_snapshots.get(name)
        if snap is None:
            return f"Error: snapshot '{name}' not found"
        for k in self.RESTRICTED:
            if k in snap:
                setattr(self._loop, k, snap[k])
        if "_runtime_vars" in snap:
            self._loop._runtime_vars = copy.deepcopy(snap["_runtime_vars"])
        self._audit("restore", name)
        return f"Restored snapshot '{name}'"

    def _list_snapshots(self) -> str:
        names = list(self._loop._config_snapshots.keys())
        if not names:
            return "No snapshots saved"
        return f"Snapshots ({len(names)}): {names}"

    # -- reset --

    def _reset(self, key: str | None) -> str:
        if err := self._validate_key(key):
            return err
        if key in self.BLOCKED:
            return f"Error: '{key}' is protected"
        if key in self.RESTRICTED:
            if key not in self._loop._config_defaults:
                return f"Error: no config default for '{key}'"
            default = self._loop._config_defaults[key]
            old = getattr(self._loop, key)
            setattr(self._loop, key, default)
            self._audit("reset", f"{key}: {old!r} -> {default!r}")
            return f"Reset {key} = {default!r} (was {old!r})"
        if key in self._loop._runtime_vars:
            old = self._loop._runtime_vars.pop(key)
            self._audit("reset", f"_runtime_vars.{key}: {old!r} -> deleted")
            return f"Deleted _runtime_vars.{key} (was {old!r})"
        return f"'{key}' is not a known property or runtime variable"
